# Generated by Django 4.2.13 on 2024-06-05 19:02

from django.conf import settings
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.hashers import make_password
from django.db import migrations


def create_super_user(apps, schema_editor):  # noqa: C901
    """Создание суперпользователя."""
    User = apps.get_model('user.User')

    email = settings.DJANGO_SUPERUSER_EMAIL
    password = settings.DJANGO_SUPERUSER_PASSWORD
    superuser = User()
    superuser.email = BaseUserManager.normalize_email(email)
    superuser.username = BaseUserManager.normalize_email(email)
    superuser.password = make_password(password)
    superuser.is_staff = True
    superuser.is_active = True
    superuser.is_superuser = True
    superuser.save()

    # FIXME: Убрать.
    user = User()
    user.email = BaseUserManager.normalize_email('is@kiout.ru')
    user.username = BaseUserManager.normalize_email('is@kiout.ru')
    user.password = make_password('QAZwsx1!')
    user.first_name = 'Игорь'
    user.last_name = 'Соколов'
    user.middle_name = 'Викорович'
    user.is_staff = False
    user.is_active = True
    user.is_superuser = False
    user.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_super_user,
            migrations.RunPython.noop,
        ),
    ]
