# Generated by Django 4.2.13 on 2024-06-05 19:02

import django.contrib.auth.validators
import django.utils.timezone
import rules.contrib.models
from django.conf import settings
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.hashers import make_password
from django.db import migrations, models

import server.apps.user.models.user


def create_super_user(apps, schema_editor):  # noqa: C901
    """Создание суперпользователя."""
    User = apps.get_model('user.User')

    email = settings.DJANGO_SUPERUSER_EMAIL
    password = settings.DJANGO_SUPERUSER_PASSWORD
    user = User()
    user.email = BaseUserManager.normalize_email(email)
    user.username = BaseUserManager.normalize_email(email)
    user.password = make_password(password)
    user.is_staff = True
    user.is_active = True
    user.is_superuser = True
    user.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_super_user,
            migrations.RunPython.noop,
        ),
    ]
