# Generated by Django 4.2.13 on 2024-05-30 08:18

from django.db import migrations, models
import django.db.models.deletion
import rules.contrib.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='InvestmentSite',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Создан'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Изменен'),
                ),
                (
                    'investment_site_id',
                    models.IntegerField(verbose_name='Id объекта'),
                ),
                (
                    'main_photo_url',
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name='Изображение объекта',
                    ),
                ),
                (
                    'photo_urls',
                    models.JSONField(
                        blank=True,
                        null=True,
                        verbose_name='Дополнительные изображения',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        blank=True, max_length=255, verbose_name='Наименование'
                    ),
                ),
                (
                    'investment_object_type',
                    models.IntegerField(
                        null=True, verbose_name='Тип инвестиционной площадки'
                    ),
                ),
                (
                    'detail_url',
                    models.CharField(
                        blank=True, verbose_name='Ссылка на investmoscom.ru'
                    ),
                ),
                (
                    'extra_data',
                    models.JSONField(
                        blank=True,
                        null=True,
                        verbose_name='Дополнительные сведения',
                    ),
                ),
                (
                    'latitude',
                    models.DecimalField(
                        decimal_places=3, max_digits=9, verbose_name='Широта'
                    ),
                ),
                (
                    'longitude',
                    models.DecimalField(
                        decimal_places=3, max_digits=9, verbose_name='Долгота'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Инвестиционная площадка',
                'verbose_name_plural': 'Инвестиционные площадки',
                'ordering': ['-id'],
                'abstract': False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Создан'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Изменен'),
                ),
                (
                    'tender_id',
                    models.CharField(
                        max_length=255, unique=True, verbose_name='Id тендера'
                    ),
                ),
                (
                    'bidding_type',
                    models.CharField(blank=True, verbose_name='Вид торгов'),
                ),
                (
                    'extra_data',
                    models.JSONField(
                        blank=True,
                        null=True,
                        verbose_name='Дополнительные сведения',
                    ),
                ),
                (
                    'detail_url',
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name='Ссылка на torgi.gov.ru',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Тендер',
                'verbose_name_plural': 'Тендеры',
                'ordering': ['-id'],
                'abstract': False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TenderLot',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Создан'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Изменен'),
                ),
                (
                    'tender_lot_id',
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name='Id лота тендера',
                    ),
                ),
                (
                    'name',
                    models.TextField(blank=True, verbose_name='Название лота'),
                ),
                (
                    'description',
                    models.TextField(blank=True, verbose_name='Название лота'),
                ),
                (
                    'extra_data',
                    models.JSONField(
                        blank=True,
                        null=True,
                        verbose_name='Дополнительные сведения',
                    ),
                ),
                (
                    'detail_url',
                    models.CharField(
                        blank=True, verbose_name='Ссылка на torgi.gov.ru'
                    ),
                ),
                (
                    'tender',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='lots',
                        to='investment_site.tender',
                        verbose_name='Тендер',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Лот тендера',
                'verbose_name_plural': 'Лоты тендера',
                'ordering': ['-id'],
                'abstract': False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
