# Generated by Django 4.2.13 on 2024-05-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(model_name='investmentsite', name='latitude',),
        migrations.RemoveField(model_name='investmentsite', name='longitude',),
        migrations.AddField(
            model_name='investmentsite',
            name='coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
