# Generated by Django 5.0.6 on 2024-06-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_object', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionform',
            name='transaction_form_type',
            field=models.CharField(
                choices=[
                    ('rent', 'Аренда'),
                    ('sale', 'Продажа'),
                    ('rent_or_sale', 'Аренда или продажа'),
                    ('not_data', 'Нет данных'),
                ],
                default=1,
                max_length=255,
                verbose_name='Тип сделки',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specializedsite',
            name='is_free_customs_zone_regime',
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name='Наличие режима свободной таможенной зоны',
            ),
        ),
    ]
