# Generated by Django 5.0.6 on 2024-06-06 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment_object', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(name='Support',),
    ]
