# Generated by Django 5.0.6 on 2024-06-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_object', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentobject',
            name='location',
            field=models.CharField(
                blank=True, max_length=400, verbose_name='Местоположение'
            ),
        ),
    ]
