# Generated by Django 5.0.6 on 2024-06-08 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            'investment_object',
            '0002_transactionform_transaction_form_type_and_more',
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specializedsite', name='minimum_rental_price',
        ),
        migrations.RemoveField(
            model_name='specializedsite', name='municipality',
        ),
        migrations.RemoveField(model_name='specializedsite', name='website',),
    ]
