# Generated by Django 5.0.6 on 2024-06-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_object', '0002_delete_support'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='infrastructure', name='availability',
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='availability',
            field=models.CharField(
                choices=[
                    ('possible_creation', 'Возможно создание'),
                    ('yes', 'Да'),
                    ('not_data', 'Нет данных'),
                ],
                default='not_data',
                max_length=255,
                verbose_name='Наличие',
            ),
        ),
        migrations.AlterField(
            model_name='investmentobject',
            name='object_type',
            field=models.IntegerField(
                choices=[
                    (1, 'Технопарк'),
                    (2, 'Технополис'),
                    (3, 'Земля'),
                    (4, 'Промплощадка'),
                    (5, 'Участки для промышленности.'),
                    (6, 'КРТ'),
                    (7, 'Тендер'),
                    (8, 'Реальный бизнес'),
                    (9, 'Нет данных'),
                ],
                default=9,
                verbose_name='Тип объекта',
            ),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='preferential_treatment',
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name='Преференциальный режим',
            ),
        ),
        migrations.AddConstraint(
            model_name='infrastructure',
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        'availability__in',
                        ['possible_creation', 'yes', 'not_data'],
                    )
                ),
                name='availability_valid',
            ),
        ),
        migrations.AddConstraint(
            model_name='investmentobject',
            constraint=models.CheckConstraint(
                check=models.Q(
                    ('object_type__in', [1, 2, 3, 4, 5, 6, 7, 8, 9])
                ),
                name='object_type_valid',
            ),
        ),
    ]
