# Generated by Django 5.0.6 on 2024-06-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_object', '0002_alter_investmentobject_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentobject',
            name='location',
            field=models.TextField(verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='investmentobject',
            name='name',
            field=models.TextField(blank=True, verbose_name='Наименование'),
        ),
    ]
