# Generated by Django 5.0.6 on 2024-06-08 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'investment_object',
            '0003_remove_specializedsite_minimum_rental_price_and_more',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentobject',
            name='economic_activities',
            field=models.ManyToManyField(
                blank=True,
                related_name='investment_objects',
                to='investment_object.economicactivity',
                verbose_name='Экономическая деятельность',
            ),
        ),
        migrations.AlterField(
            model_name='investmentobject',
            name='transaction_form',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='investment_objects',
                to='investment_object.transactionform',
                verbose_name='Форма сделки',
            ),
        ),
    ]
