# Generated by Django 5.0.6 on 2024-06-08 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'investment_object',
            '0004_alter_investmentobject_economic_activities_and_more',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentobject',
            name='transaction_form',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='investment_objects',
                to='investment_object.transactionform',
                verbose_name='Форма сделки',
            ),
        ),
    ]
