# Generated by Django 5.0.6 on 2024-06-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_cabinet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='filter',
            field=models.JSONField(
                blank=True,
                null=True,
                verbose_name='Фильтры для инвестиционных объектов',
            ),
        ),
    ]
