# Generated by Django 5.0.6 on 2024-06-09 16:08

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal_cabinet', '0001_initial'),
        ('service_interaction', '0001_initial'),
        ('taggit', '0005_auto_20220424_2025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='topics',
            field=models.ManyToManyField(
                blank=True,
                related_name='subscriptions',
                to='service_interaction.topic',
                verbose_name='Тема',
            ),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='subscriptions',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Пользователь',
            ),
        ),
        migrations.AddField(
            model_name='business',
            name='sub_sector',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='business',
                to='personal_cabinet.subsector',
                verbose_name='Подотрасль хозяйственной деятельности',
            ),
        ),
        migrations.AddField(
            model_name='territoriallocation',
            name='tags',
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='taggit.TaggedItem',
                to='taggit.Tag',
                verbose_name='Tags',
            ),
        ),
        migrations.AddField(
            model_name='business',
            name='territorial_location',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='businesses',
                to='personal_cabinet.territoriallocation',
                verbose_name='Территориальное положение бизнеса',
            ),
        ),
        migrations.AddConstraint(
            model_name='selectionrequest',
            constraint=models.UniqueConstraint(
                condition=models.Q(('is_actual', True)),
                fields=('is_actual',),
                name='unique_is_actual_for_selection_request',
            ),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(
                check=models.Q(('owner_type__in', ['user', 'bot'])),
                name='owner_type_valid',
            ),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        'subscription_type__in',
                        [
                            'investment_object',
                            'service_support',
                            'topic',
                            'event',
                        ],
                    )
                ),
                name='subscription_type_valid',
            ),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(
                fields=('subscription_type', 'user'),
                name='unique_subscription_type_for_user',
            ),
        ),
        migrations.AddConstraint(
            model_name='business',
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        'business_type__in',
                        ['legal', 'individual', 'physical', ''],
                    )
                ),
                name='business_type_valid',
            ),
        ),
        migrations.AddConstraint(
            model_name='business',
            constraint=models.CheckConstraint(
                check=models.Q(
                    ('tax_system_type__in', ['osn', 'ysn', 'patent'])
                ),
                name='tax_system_type_valid',
            ),
        ),
    ]
