# Generated by Django 5.0.6 on 2024-06-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_cabinet', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='email',
            field=models.EmailField(
                max_length=255, verbose_name='Почта пользователя'
            ),
            preserve_default=False,
        ),
    ]
