# Generated by Django 5.0.6 on 2024-06-07 01:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_cabinet', '0002_rename_type_business_type_business'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(model_name='business', name='type_valid',),
        migrations.AddConstraint(
            model_name='business',
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        'type_business__in',
                        ['legal', 'individual', 'physical', ''],
                    )
                ),
                name='type_business_valid',
            ),
        ),
    ]
