# Generated by Django 5.0.6 on 2024-06-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_cabinet', '0002_message_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectionrequest',
            name='is_bot_response_waiting',
            field=models.BooleanField(
                default=False,
                verbose_name='Ожидает ли запрос ответ от бота или нет',
            ),
        ),
    ]
