# Generated by Django 5.0.6 on 2024-06-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_cabinet', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(model_name='message', name='filter',),
        migrations.AddField(
            model_name='message',
            name='bot_filter',
            field=models.JSONField(
                blank=True,
                null=True,
                verbose_name='Фильтры для инвестиционных объектов от бота',
            ),
        ),
        migrations.AddField(
            model_name='message',
            name='user_filter',
            field=models.JSONField(
                blank=True,
                null=True,
                verbose_name='Фильтры для инвестиционных объектов от пользователя',
            ),
        ),
        migrations.DeleteModel(name='SelectedEntity',),
    ]
