# Generated by Django 5.0.6 on 2024-06-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_cabinet', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='message', name='owner_type_valid',
        ),
        migrations.AlterField(
            model_name='message',
            name='owner_type',
            field=models.CharField(
                choices=[
                    ('user', 'Пользователь'),
                    ('assistant', 'assistant'),
                    ('system', 'Система'),
                ],
                default='user',
                max_length=255,
                verbose_name='Владелец',
            ),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(
                check=models.Q(
                    ('owner_type__in', ['user', 'assistant', 'system'])
                ),
                name='owner_type_valid',
            ),
        ),
    ]
