# Generated by Django 5.0.6 on 2024-06-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_cabinet', '0003_remove_business_type_valid_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(model_name='message', name='owner_type',),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(
                check=models.Q(('owner_type__in', ['user', 'bot'])),
                name='owner_type_valid',
            ),
        ),
    ]
