# Generated by Django 5.0.6 on 2024-06-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_cabinet', '0003_subscription_email'),
    ]

    operations = [
        migrations.RemoveField(model_name='business', name='okved',),
        migrations.AddField(
            model_name='business',
            name='okved_code',
            field=models.CharField(
                blank=True, max_length=255, verbose_name='Код ОКВЕД'
            ),
        ),
    ]
