# Generated by Django 5.0.6 on 2024-06-11 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            'personal_cabinet',
            '0003_remove_message_filter_message_bot_filter_and_more',
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='selectionrequest',
            name='unique_is_actual_for_selection_request',
        ),
    ]
