# Generated by Django 5.0.6 on 2024-06-11 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'personal_cabinet',
            '0004_remove_selectionrequest_unique_is_actual_for_selection_request',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='children',
                to='personal_cabinet.message',
                verbose_name='Родительское сообщение',
            ),
        ),
    ]
