# Generated by Django 4.2.13 on 2024-05-30 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(name='Area',),
    ]
