# Generated by Django 5.0.6 on 2024-06-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_servicesupport_delete_support_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemreport',
            name='theme_name',
            field=models.TextField(verbose_name='Название темы'),
        ),
    ]
