# Generated by Django 5.0.6 on 2024-06-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'investment_object',
            '0003_remove_infrastructure_availability_and_more',
        ),
        ('support', '0004_alter_problemreport_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='servicesupport', name='type_service',
        ),
        migrations.AddConstraint(
            model_name='servicesupport',
            constraint=models.CheckConstraint(
                check=models.Q(
                    ('type_service__in', ['service', 'support_measure'])
                ),
                name='type_service_valid',
            ),
        ),
    ]
