# Generated by Django 4.2.1 on 2023-06-10 07:30

import django.db.models.deletion
import rules.contrib.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hincal', '0003_remove_archive_lower_tax_margin_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='personal_income_rate',
            field=models.FloatField(default=0.13, verbose_name='Размер НДФЛ'),
        ),
        migrations.AlterField(
            model_name='businessindicator',
            name='year',
            field=models.PositiveIntegerField(
                verbose_name='Год, к которому относятся показатели'
            ),
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Создан'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Изменен'),
                ),
                (
                    'year',
                    models.PositiveIntegerField(
                        verbose_name='Год, к которому относятся показатели'
                    ),
                ),
                (
                    'volume_of_sales',
                    models.FloatField(
                        null=True, verbose_name='Объем реализации, тыс. руб.'
                    ),
                ),
                (
                    'growth_rate',
                    models.FloatField(
                        null=True, verbose_name='Темп роста выручки за год'
                    ),
                ),
                (
                    'sector',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='statistics',
                        to='hincal.sector',
                        verbose_name='Сектор',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистики',
                'ordering': ['-id'],
                'abstract': False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='statistic',
            constraint=models.UniqueConstraint(
                fields=('year', 'sector'),
                name='unique_year_for_sector_statistic',
            ),
        ),
    ]
