# Generated by Django 5.0.6 on 2024-06-09 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_interaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(model_name='event', name='content_type',),
        migrations.RemoveField(model_name='event', name='object_id',),
    ]
