# Generated by Django 5.0.6 on 2024-06-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_interaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.ImageField(
                blank=True, upload_to='media', verbose_name='Фотография'
            ),
        ),
    ]
