# Generated by Django 5.0.6 on 2024-06-11 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_interaction', '0002_event_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={
                'ordering': ['-id'],
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
    ]
